---
driver_plugin: vagrant
        
provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
  - name: ubuntu-12.04
    run_list:
      - yum::default

  - name: centos-6.4
    run_list:
      - yum::default

suites:
- name: default
  run_list:
  - recipe[yum::default]
  attributes: {}
